#ifndef PROC_JOB_H
#define PROC_JOB_H

/*
 * proc_job.h — Job control support.
 *
 * APUE Chapter 9, Sections 9.8, 9.9
 *
 * Job Control Requirements:
 *   1. A shell that supports job control.
 *   2. Terminal driver in kernel that supports job control.
 *   3. Kernel support for job-control signals.
 *
 * A "job" is a collection of processes, often a pipeline.
 *
 * Job-control signals generated by the terminal driver:
 *   SIGINT  — interrupt key (Ctrl-C / DELETE)
 *             → sent to foreground process group
 *   SIGQUIT — quit key (Ctrl-\)
 *             → sent to foreground process group + core dump
 *   SIGTSTP — suspend key (Ctrl-Z)
 *             → sent to foreground process group; stops them
 *
 * Background process I/O signals:
 *   SIGTTIN — background job reads from controlling terminal
 *             → terminal driver sends this; normally stops bg job
 *             → shell uses fg to bring it forward + SIGCONT
 *   SIGTTOU — background job writes to controlling terminal
 *             → only if TOSTOP terminal flag is set (stty tostop)
 *             → stops background job
 *
 * Job-control shell behavior:
 *   Foreground job: placed in its own process group;
 *                   shell waits for it; tcsetpgrp sets fg group.
 *   Background job: placed in its own process group;
 *                   shell does NOT wait for it;
 *                   shell sets itself as foreground group.
 *
 * Without job control (Bourne shell):
 *   Background job's stdin is redirected to /dev/null.
 *   Background job stays in same process group as shell.
 */

#include <unistd.h>
#include <signal.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <termios.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <fcntl.h>

/* Maximum number of jobs tracked */
#define JOB_MAX 64

/* Job states */
typedef enum {
    JOB_RUNNING    = 1,
    JOB_STOPPED    = 2,
    JOB_DONE       = 3
} job_state_t;

/* Single process in a job */
typedef struct proc_info {
    pid_t          pi_pid;
    int            pi_status;
    struct proc_info *pi_next;
} proc_info_t;

/* Job descriptor */
typedef struct job {
    int          j_id;          /* shell job number (1-based)  */
    pid_t        j_pgid;        /* process group ID of job     */
    job_state_t  j_state;       /* current job state           */
    char         j_cmd[256];    /* command string              */
    proc_info_t *j_procs;       /* linked list of processes    */
    int          j_active;      /* 1 = slot in use             */
} job_t;

/* Global job table */
extern job_t job_table[JOB_MAX];
extern int   job_count;

/* ── Job table operations ──────────────────────────────── */

/*
 * job_add()
 *
 * Adds a new job to the job table.
 *
 * @param pgid  Process group ID of the new job.
 * @param cmd   Command string for display.
 *
 * Returns job ID (1-based) on success, -1 if table full.
 */
int job_add(pid_t pgid, const char *cmd);

/*
 * job_remove()
 *
 * Removes a job from the job table by job ID.
 */
void job_remove(int job_id);

/*
 * job_find_by_pgid()
 *
 * Returns pointer to job with given PGID, or NULL.
 */
job_t *job_find_by_pgid(pid_t pgid);

/*
 * job_print_all()
 *
 * Prints all active jobs similar to the shell's jobs command.
 */
void job_print_all(void);

/* ── Job control shell operations ──────────────────────── */

/*
 * job_launch_foreground()
 *
 * Launches a new foreground job.
 * Steps:
 *   1. fork()
 *   2. Child: setpgid(0,0) → new process group.
 *             tcsetpgrp(STDIN_FILENO, child_pgid) → make fg.
 *             execvp(argv[0], argv).
 *   3. Parent: setpgid(child_pid, child_pid) (race avoidance).
 *              Wait for child (job_wait_foreground).
 *              Restore shell as foreground.
 *
 * @param argv  Null-terminated argument array.
 *
 * Returns exit status of child.
 */
int job_launch_foreground(char *const argv[]);

/*
 * job_launch_background()
 *
 * Launches a new background job.
 * Steps:
 *   1. fork()
 *   2. Child: setpgid(0,0) → new process group.
 *             execvp(argv[0], argv).
 *   3. Parent: setpgid(child_pid, child_pid) (race avoidance).
 *              Add to job table.
 *              Print "[N] PID".
 *              Return immediately.
 *
 * @param argv  Null-terminated argument array.
 *
 * Returns job ID.
 */
int job_launch_background(char *const argv[]);

/*
 * job_wait_foreground()
 *
 * Waits for the foreground job (process group pgid) to stop
 * or terminate.  Collects status for each process.
 *
 * @param pgid  Process group ID of foreground job.
 *
 * Returns final exit status.
 */
int job_wait_foreground(pid_t pgid);

/*
 * job_continue()
 *
 * Sends SIGCONT to the process group of job j and optionally
 * makes it the foreground job.
 *
 * @param j           Job to continue.
 * @param foreground  1 = bring to foreground, 0 = background.
 */
void job_continue(job_t *j, int foreground);

/*
 * job_update_status()
 *
 * Called after waitpid() — updates the state of the job
 * associated with the changed process.
 *
 * @param pid     PID of the process that changed.
 * @param status  Status returned by waitpid().
 */
void job_update_status(pid_t pid, int status);

/*
 * job_check_background()
 *
 * Checks for background jobs that have changed state (using
 * WNOHANG) and prints notifications, similar to what a shell
 * does just before printing its prompt.
 */
void job_check_background(void);

/*
 * job_restore_shell_tty()
 *
 * Restores the shell's process group as the foreground process
 * group on the controlling terminal.
 *
 * Called after a foreground job terminates or stops.
 */
void job_restore_shell_tty(void);

#endif /* PROC_JOB_H */
