#ifndef __INTERRUPTS_EXCEPTIONS__H
#define __INTERRUPTS_EXCEPTIONS__H

/*
Interrupts are often divided into synchronous and asynchronous interrupts:
• Synchronous interrupts are produced by the CPU control unit while executing
instructions and are called synchronous because the control unit issues them
only after terminating the execution of an instruction.
• Asynchronous interrupts are generated by other hardware devices at arbitrary
times with respect to the CPU clock signals.

occasionally use the term “interrupt signal” to designate both types together (synchronous
as well as asynchronous)

Interrupts are issued by interval timers and I/O devices; for instance, the arrival of a
keystroke from a user sets off an interrupt.

Exceptions, on the other hand, are caused either by programming errors or by anomalous
conditions that must be handled by the kernel. In the first case, the kernel handles
the exception by delivering to the current process one of the signals familiar to
every Unix programmer. In the second case, the kernel performs all the steps needed
to recover from the anomalous condition, such as a Page Fault or a request—via an
assembly language instruction such as int or sysenter—for a kernel service.

Each interrupt or exception is identified by a number ranging from 0 to 255;

The vectors of nonmaskable interrupts and
exceptions are fixed, while those of maskable interrupts can be altered by programming
the Interrupt Controller

All existing IRQ
lines are connected to the input pins of a hardware circuit called the Programmable
Interrupt Controller
*/
#define Synchronous  //in 8086 arch called exceptions
#define Asynchronous //in 8086 arch called interrupts


#define InterruptDescriptorTable



#ifdef Synchronous

#define Processor-detected exceptions
#define Programmed exceptions

#ifdef Processor-detected exceptions
#define Faults //Can generally be corrected; once corrected, the program is allowed to restart with no loss of continuity.
#define Traps //Reported immediately following the execution of the trapping instruction; after the kernel returns control to the program, it is allowed to continue its execution with no loss of continuity.
/*
Aborts:A serious error occurred; the control unit is in trouble, and it may be
unable to store in the eip register the precise location of the instruction
causing the exception. Aborts are used to report severe errors, such as
hardware failures and invalid or inconsistent values in system tables.
*/
#define Aborts 
#endif // end of Processor-detected exceptions


#ifdef Programmed exceptions //Occur at the request of the programmer.

#endif // end of Programmed exceptions

#endif  // end of Synchronous




#ifdef Asynchronous //interrupts

#define Maskable interrupts  //All Interrupt Requests (IRQs) issued by I/O devices give rise to maskable interrupts.
#define Nonmaskable interrupts //Only a few critical events (such as hardware failures)

#endif  // end of Asynchronous


#define Programmable Interrupt Controller (APIC) //mostly work for single CPU
#define The Advanced Programmable Interrupt Controller (APIC) // capable for more than 2 CPU. fully exploiting the parallelism of the SMParchitecture.
/* Interrupt requests coming from external hardware devices can be distributed among
the available CPUs in two ways: */
#define Static distribution
/*The IRQ signal is delivered to the local APICs listed in the corresponding Redirection
Table entry. The interrupt is delivered to one specific CPU, to a subset of
CPUs, or to all CPUs at once (broadcast mode).*/
#define Dynamic distribution
/*The IRQ signal is delivered to the local APIC of the processor that is executing
the process with the lowest priority.
the load is distributed between
them using a technique called arbitration. Each CPU is assigned a different arbitration
priority ranging from 0 (lowest) to 15 (highest) in the arbitration priority
register of the local APIC.
*/

#define TPR //task priority register


enum Exceptions{
    Divideerror; //0 - “Divide error” (fault) Raised when a program issues an integer division by 0.
    Debug ; //1- “Debug” (trap or fault) Raised when the TF flag of eflags is set
    Notused; //2 - Not used Reserved for nonmaskable interrupts
    Breakpoint; //3 - “Breakpoint” (trap)
Caused by an int3 (breakpoint) instruction (usually inserted by a debugger).
    Overflow; //4 - “Overflow” (trap)
An into (check for overflow) instruction has been executed while the OF (overflow)
flag of eflags is set.
    Boundscheck; //5 - “Bounds check” (fault)
A bound (check on address bound) instruction is executed with the operand outside
of the valid address bounds.
    Invalidopcode ; //6 - “Invalid opcode” (fault)
The CPU execution unit has detected an invalid opcode (the part of the machine
instruction that determines the operation performed).
    Device not available; //7 - “Device not available” (fault)
An ESCAPE, MMX, or SSE/SSE2 instruction has been executed with the TS flag
of cr0 set (see the section “Saving and Loading the FPU, MMX, and XMM Registers”
in Chapter 3).
    Double fault;//8 - “Double fault” (abort)
Normally, when the CPU detects an exception while trying to call the handler
for a prior exception, the two exceptions can be handled serially. In a few cases,
however, the processor cannot handle them serially, so it raises this exception.
    Coprocessor segment overrun;//9 - “Coprocessor segment overrun” (abort)
Problems with the external mathematical coprocessor (applies only to old 80386
microprocessors).
    Invalid TSS; //10 - “Invalid TSS” (fault)
The CPU has attempted a context switch to a process having an invalid Task
State Segment.
    Segment not present; //11 - “Segment not present” (fault)
A reference was made to a segment not present in memory (one in which the
Segment-Present flag of the Segment Descriptor was cleared).
    Stack segment fault; //12 - “Stack segment fault” (fault)
The instruction attempted to exceed the stack segment limit, or the segment
identified by ss is not present in memory.
    General protection;//13 - “General protection” (fault)
One of the protection rules in the protected mode of the 80×86 has been
violated.
    Page Fault; //14 - “Page Fault” (fault)
The addressed page is not present in memory, the corresponding Page Table
entry is null, or a violation of the paging protection mechanism has occurred.
    Reserved by Intel; //15 - Reserved by Intel
    Floating-point error;//16 - “Floating-point error” (fault)
The floating-point unit integrated into the CPU chip has signaled an error condition,
such as numeric overflow or division by 0.*
    Alignment check; //17 - “Alignment check” (fault)
The address of an operand is not correctly aligned (for instance, the address of a
long integer is not a multiple of 4).
    “Machine check; //18 - “Machine check” (abort)
A machine-check mechanism has detected a CPU or bus error.
    SIMD floating point exception; // 19 - “SIMD floating point exception” (fault) The SSE or SSE2 unit integrated in theThe SSE or SSE2 unit integrated in the CPU chip has signaled an error condition on a floating-point operation
};


/*
Table. Signals sent by the exception handlers
# Exception Exception handler Signal
0 Divide error divide_error( ) SIGFPE
1 Debug debug( ) SIGTRAP
2 NMI nmi( ) None
3 Breakpoint int3( ) SIGTRAP
4 Overflow overflow( ) SIGSEGV
5 Bounds check bounds( ) SIGSEGV
6 Invalid opcode invalid_op( ) SIGILL
7 Device not available device_not_available( ) None
8 Double fault doublefault_fn() None
9 Coprocessor segment overrun coprocessor_segment_overrun( ) SIGFPE
10 Invalid TSS invalid_TSS( ) SIGSEGV
11 Segment not present segment_not_present( ) SIGBUS
12 Stack segment fault stack_segment( ) SIGBUS
13 General protection general_protection( ) SIGSEGV
14 Page Fault page_fault( ) SIGSEGV
15 Intel-reserved None None
16 Floating-point error coprocessor_error( ) SIGFPE
17 Alignment check alignment_check( ) SIGBUS
18 Machine check machine_check() None
19 SIMD floating point simd_coprocessor_error() SIGFPE
*/


#define IDT // Interrupt Descriptor Table. The IDT must be properly initialized before the kernel enables interrupts. IDT format is similar to that of the GDT and the LDTs.
struct InterruptDescriptorTable{ //8-byte

};

/*/Includes the TSS selector of the process that must replace the current one when an interrupt signal occurs.*/
struct TaskGateDescriptor{ 
    //InterruptDescriptorTable TaskGD;
    reserved:0-15;
    TSSSEGMENTSelector:16-31;
    reserved:32-39;

};

/*Includes the Segment Selector and the offset inside the segment of an interrupt
or exception handler. While transferring control to the proper segment, the processor
clears the IF flag, thus disabling further maskable interrupts.*/
struct InterruptGateDescriptor{
    //InterruptDescriptorTable IntGD;
};

/*Similar to an interrupt gate, except that while transferring control to the proper
segment, the processor does not modify the IF flag.*/
struct TrapGateDescriptor{
    //InterruptDescriptorTable TrapGD
};

#define Hardware Handling of Interrupts and Exceptions

#define Nested Execution of Exception and Interrupt Handlers
/* Interrupt, Trap, and System Gates */

#define Initializing the Interrupt Descriptor Table


#define Interrupt, Trap, and System Gates


/*
struct ITSG //Interrupt, Trap, and System Gates
{
    Interrupt gate:An Intel interrupt gate that cannot be accessed by a User Mode process (the
gate’s DPL field is equal to 0). All Linux interrupt handlers are activated by
means of interrupt gates, and all are restricted to Kernel Mode.
    System gate:An Intel trap gate that can be accessed by a User Mode process (the gate’s DPL
field is equal to 3). The three Linux exception handlers associated with the vectors
4, 5, and 128 are activated by means of system gates, so the three assembly
language instructions into, bound, and int $0x80 can be issued in User Mode.
    System interrupt gate:An Intel interrupt gate that can be accessed by a User Mode process (the gate’s
DPL field is equal to 3). The exception handler associated with the vector 3 is
activated by means of a system interrupt gate, so the assembly language instruction
int3 can be issued in User Mode.
    Trap gate:An Intel trap gate that cannot be accessed by a User Mode process (the gate’s
DPL field is equal to 0). Most Linux exception handlers are activated by means
of trap gates.
    Task gate:An Intel task gate that cannot be accessed by a User Mode process (the gate’s
DPL field is equal to 0). The Linux handler for the “Double fault” exception is
activated by means of a task gate.

};
*/

set_intr_gate(n,addr); 
/*Inserts an interrupt gate in the nth IDT entry. The Segment Selector inside the
gate is set to the kernel code’s Segment Selector. The Offset field is set to addr,
which is the address of the interrupt handler. The DPL field is set to 0.*/

set_system_gate(n,addr);
/*
Inserts a trap gate in the nth IDT entry. The Segment Selector inside the gate is
set to the kernel code’s Segment Selector. The Offset field is set to addr, which is
the address of the exception handler. The DPL field is set to 3.
*/

set_system_intr_gate(n,addr);
/*Inserts an interrupt gate in the nth IDT entry. The Segment Selector inside the
gate is set to the kernel code’s Segment Selector. The Offset field is set to addr,
which is the address of the exception handler. The DPL field is set to 3.*/

set_trap_gate(n,addr);
/*Similar to the previous function, except the DPL field is set to 0.*/

set_task_gate(n,gdt);
/*Inserts a task gate in the nth IDT entry. The Segment Selector inside the gate
stores the index in the GDT of the TSS containing the function to be activated.
The Offset field is set to 0, while the DPL field is set to 3.*/


#define Preliminary Initialization of the IDT



#define Exception Handling 
#ifdef Exception Handling 
#define Saving the Registers for the Exception Handler
#define Entering and Leaving the Exception Handler
#endif // end of Exception Handling 



#define Interrupt Handling
#ifdef Interrupt Handling

#define I/O interrupts
#ifdef I/O interrupts
#define IRQ sharing // The interrupt handler executes several interrupt service routines (ISRs). Each ISR is a function related to a single device sharing the IRQ line.
#define  IRQ dynamic allocation//An IRQ line is associated with a device driver at the last possible moment; for instance, the IRQ line of the floppy device is allocated only when a user accesses the floppy disk device.
#define Critical //
#define Noncritica
#define Noncritical deferrable

#define Interrupt vectors
#ifdef Interrupt vectors
struct intrruptvector{
    0–19 (0x0–0x13) //Nonmaskable interrupts and exceptions
    20–31 (0x14–0x1f) //Intel-reserved
    32–127 (0x20–0x7f) //External interrupts (IRQs)
    128 (0x80) //Programmed exception for system calls (see Chapter 10)
    129–238 (0x81–0xee) //External interrupts (IRQs)
    239 (0xef) //Local APIC timer interrupt (see Chapter 6)
    240 (0xf0) //Local APIC thermal interrupt (introduced in the Pentium 4 models)
    241–250 (0xf1–0xfa) //Reserved by Linux for future use
    251–253 (0xfb–0xfd) //Interprocessor interrupts (see the section “Interprocessor Interrupt Handling” later in this chapter)
    254 (0xfe) //Local APIC error interrupt (generated when the local APIC detects an erroneous condition)
    255 (0xff) //Local APIC spurious interrupt (generated if the CPU masks an interrupt while the hardware device raises it)
};
/*
Table . An example of IRQ assignment to I/O devices
IRQ INT Hardware device
0 32 Timer
1 33 Keyboard
2 34 PIC cascading
3 35 Second serial port
4 36 First serial port
6 38 Floppy disk
8 40 System clock
10 42 Network interface
11 43 USB port, sound card
12 44 PS/2 mouse
13 45 Mathematical coprocessor
14 46 EIDE disk controller’s first chain
15 47 EIDE disk controller’s second chain
*/

struct irq_desc_t 
{
    handler //Points to the PIC object (hw_irq_controller descriptor) that services the IRQ line.
    handler_data //Pointer to data used by the PIC methods.
    action //Identifies the interrupt service routines to be invoked when the IRQ occurs. The field points to the first element of the list of irqaction descriptors associated with the IRQ. The irqaction descriptor is described later in the chapter.
    status //A set of flags describing the IRQ line status (see Table 4-5). depth Shows 0 if the IRQ line is enabled and a positive value if it has been disabled at least once.
    irq_count //Counter of interrupt occurrences on the IRQ line (for diagnostic use only).
    irqs_unhandled //Counter of unhandled interrupt occurrences on the IRQ line (for diagnostic use only).
    lock //A spin lock used to serialize the accesses to the IRQ descriptor and to the PIC (see Chapter 5).
};

//Flags describing the IRQ line status
enum IRQlinestatus{
    IRQ_INPROGRESS //A handler for the IRQ is being executed.
    IRQ_DISABLED //The IRQ line has been deliberately disabled by a device driver.
    IRQ_PENDING //An IRQ has occurred on the line; its occurrence has been acknowledged to the PIC, but it has not yet been serviced by the kernel.
    IRQ_REPLAY //The IRQ line has been disabled but the previous IRQ occurrence has not yet been acknowledged to the PIC.
    IRQ_AUTODETECT //The kernel is using the IRQ line while performing a hardware device probe.
    IRQ_WAITING //The kernel is using the IRQ line while performing a hardware device probe; moreover, the corresponding interrupt has not been raised.
    IRQ_LEVEL //Not used on the 80 × 86 architecture.
    IRQ_MASKED //Not used.
    IRQ_PER_CPU //Not used on the 80 × 86 architecture.
};

init_IRQ( );
disable_irq(); 
disable_irq_nosync();
setup_idt();


//Table . Fields of the irqaction descriptor
//Field name Description
struct irqaction{
    handler //Points to the interrupt service routine for an I/O device. This is the key field that allows many devices to share the same IRQ.
    flags //This field includes a few fields that describe the relationships between the IRQ line and the I/O device (see in below Table 4-7). 
    mask //Not used.
    name //The name of the I/O device (shown when listing the serviced IRQs by reading the /proc/interrupts file).
    dev_id //A private field for the I/O device. Typically, it identifies the I/O device itself (for instance, it could be equal to its major and minor numbers; see the section “Device Files” in Chapter 13), or it points to the device driver’s data.
    next //Points to the next element of a list of irqaction descriptors. The elements in the list refer to hardware devices that share the same IRQ.
    irq //IRQ line.
    dir //Points to the descriptor of the /proc/irq/n directory associated with the IRQn
};

//Table 4-7. Flags of the irqaction descriptor
//Flag name Description
enum irqaction{
    SA_INTERRUPT //The handler must execute with interrupts disabled.
    SA_SHIRQ //The device permits its IRQ line to be shared with other devices.
    SA_SAMPLE_RANDOM //The device may be considered a source of events that occurs randomly; it can thus be used by the kernel random number generator. (Users can access this feature by taking random numbers from the /dev/random and /dev/urandom device files.)
};

//Table 4-8. Fields of the irq_cpustat_t structure
//Field name Description
struct irq_cpustat_t{// to keep track what each cpu doing
    __softirq_pending //Set of flags denoting the pending softirqs (see the section “Softirqs” later in this chapter)
    idle_timestamp //Time when the CPU became idle (significant only if the CPU is currently idle)
    __nmi_count //Number of occurrences of NMI interrupts
    apic_timer_irqs //Number of occurrences of local APIC timer interrupts (see Chapter 6)
};

//During system bootstrap, the booting CPU executes the setup_IO_APIC_irqs() function to initialize the I/O APIC chip.
setup_local_APIC();
//The hardirq_ctx and softirq_ctx arrays allow the kernel to quickly determine the hard IRQ stack and soft IRQ stack of a given CPU, respectively: they contain pointers to the corresponding irq_ctx elements.
#define Saving the registers for the interrupt handler


do_IRQ( );
__do_IRQ();
{
    IRQ_DISABLED is set;
    IRQ_INPROGRESS is set;
    irq_desc[irq].action is NULL;
}
enable_irq();
handle_IRQ_event();

#endif //end of Interrupt vectors

#endif // end of I/O interrupts

#define Timer interrupts
#ifdef Timer interrupts

#endif // end of Timer interrupts

#define Interprocessor interrupts
#ifdef Interprocessor interrupts
#define Interprocessor Interrupt Handling //an interprocessor interrupt (IPI) is delivered not through an IRQ line, but directly as a message on the bus that connects the local APIC of all CPUs
CALL_FUNCTION_VECTOR (vector 0xfb); //Sent to all CPUs but the sender, forcing those CPUs to run a function passed by the sender. The corresponding interrupt handler is named call_function_ interrupt( )
RESCHEDULE_VECTOR (vector 0xfc)// When a CPU receives this type of interrupt, the corresponding handler—named reschedule_interrupt()—limits itself to acknowledging the interrupt.
INVALIDATE_TLB_VECTOR (vector 0xfd)// Sent to all CPUs but the sender, forcing them to invalidate their Translation Lookaside Buffers. The corresponding handler, named invalidate_interrupt( ), flushes some TLB entries of the processor as described in the section “Handling the Hardware Cache and the TLB” in

//Thanks to the following group of functions, issuing interprocessor interrupts (IPIs) becomes an easy task:
send_IPI_all( )// Sends an IPI to all CPUs (including the sender)
send_IPI_allbutself( )// Sends an IPI to all CPUs except the sender
send_IPI_self( )//Sends an IPI to the sender CPU
send_IPI_mask()// Sends an IPI to a group of CPUs specified by a bit mask

#define Softirqs and Tasklets // Softirqs and tasklets are strictly correlated, because tasklets are implemented on top of softirqs.
/*Softirqs are statically allocated (i.e., defined at compile time), while tasklets can also
be allocated and initialized at runtime (for instance, when loading a kernel module).
Softirqs can run concurrently on several CPUs, even if they are of the same type.
Thus, softirqs are reentrant functions and must explicitly protect their data structures
with spin locks. Tasklets do not have to worry about this, because their execution
is controlled more strictly by the kernel. Tasklets of the same type are always
serialized: in other words, the same type of tasklet cannot be executed by two CPUs
at the same time. However, tasklets of different types can be executed concurrently
on several CPUs. Serializing the tasklet simplifies the life of device driver developers,
because the tasklet function needs not be reentrant.*/
//Generally speaking, four kinds of operations can be performed on deferrable functions:
Initialization
/*Defines a new deferrable function; this operation is usually done when the kernel
initializes itself or a module is loaded.*/
Activation
/*Marks a deferrable function as “pending”—to be run the next time the kernel
schedules a round of executions of deferrable functions. Activation can be done
at any time (even while handling interrupts).*/
Masking
/*Selectively disables a deferrable function so that it will not be executed by the kernel
even if activated. We’ll see in the section “Disabling and Enabling Deferrable
Functions” in Chapter 5 that disabling deferrable functions is sometimes essential.*/
Execution
/*Executes a pending deferrable function together with all other pending deferrable
functions of the same type; execution is performed at well-specified times,
explained later in the section “Softirqs.”*/

#define Softirqs
//Table 4-9. Softirqs used in
//Softirq Index (priority) Description
enum{
HI_SOFTIRQ 0 //Handles high priority tasklets
TIMER_SOFTIRQ 1 //Tasklets related to timer interrupts
NET_TX_SOFTIRQ 2 //Transmits packets to network cards
NET_RX_SOFTIRQ 3 //Receives packets from network cards
SCSI_SOFTIRQ 4 //Post-interrupt processing of SCSI commands
TASKLET_SOFTIRQ 5 //Handles regular tasklets
}

/*Table 4-10. Subfields of the preempt_count field (continues)
Bits Description
0–7 Preemption counter (max value = 255)
8–15 Softirq counter (max value = 255).
16–27 Hardirq counter (max value = 4096)
28 PREEMPT_ACTIVE flag
*/


local_softirq_pending();
raise_softirq();
in_interrupt();
wakeup_softirqd();
do_softirq();
__do_softirq();



#define Tasklets
/*
Table 4-11. The fields of the tasklet descriptor
Field name Description
next Pointer to next descriptor in the list
state Status of the tasklet
count Lock counter
func Pointer to the tasklet function
data An unsigned long integer that may be used by the tasklet function
*/

#defne Work Queues
/*
Table 4-12. The fields of the cpu_workqueue_struct structure
Field name Description
lock Spin lock used to protect the structure
remove_sequence Sequence number used by flush_workqueue()
insert_sequence Sequence number used by flush_workqueue()
worklist Head of the list of pending functions
more_work Wait queue where the worker thread waiting for more work to be done sleeps
work_done Wait queue where the processes waiting for the work queue to be flushed sleep
wq Pointer to the workqueue_struct structure containing this descriptor
thread Process descriptor pointer of the worker thread of the structure
run_depth Current execution depth of run_workqueue() (this field may become greater than one
when a function in the work queue list blocks)
*/

/*
Table 4-13. The fields of the work_struct structure
Field name Description
pending Set to 1 if the function is already in a work queue list, 0 otherwise
entry Pointers to next and previous elements in the list of pending functions
func Address of the pending function
data Pointer passed as a parameter to the pending function
wq_data Usually points to the parent cpu_workqueue_struct descriptor
timer Software timer used to delay the execution of the pending function
*/

create_workqueue("foo");

/*
Table 4-14. Helper functions for the predefined work queue
Predefined work queue function Equivalent standard work queue function
schedule_work(w) queue_work(keventd_wq,w)
schedule_delayed_work(w,d) queue_delayed_work(keventd_wq,w,d) (on any CPU)
schedule_delayed_work_on(cpu,w,d) queue_delayed_work(keventd_wq,w,d) (on a given CPU)
flush_scheduled_work() flush_workqueue(keventd_wq)
*/

#endif // end of Interprocessor interrupts


#endif // end of Interrupt Handling

//Returning from Interrupts and Exceptions
Number of kernel control paths being concurrently executed//
If there is just one, the CPU must switch back to User Mode.
Pending process switch requests//
If there is any request, the kernel must perform process scheduling; otherwise,
control is returned to the current process.
Pending signals//
If a signal is sent to the current process, it must be handled.
Single-step mode//
If a debugger is tracing the execution of the current process, single-step mode
must be restored before switching back to User Mode.
Virtual-8086 mode//
If the CPU is in virtual-8086 mode, the current process is executing a legacy Real
Mode program, thus it must be handled in a special way.

/*
A few flags are used to keep track of pending process switch requests, of pending signals,
and of single step execution; they are stored in the flags field of the thread_
info descriptor.
*/
/*
Table 4-15. The flags field of the thread_info descriptor (continues)
Flag name Description
TIF_SYSCALL_TRACE System calls are being traced
TIF_NOTIFY_RESUME Not used in the 80x86 platform
TIF_SIGPENDING The process has pending signals
TIF_NEED_RESCHED Scheduling must be performed
TIF_SINGLESTEP Restore single step execution on return to User Mode
TIF_IRET Force return from system call via iret rather than sysexit
TIF_SYSCALL_AUDIT System calls are being audited
TIF_POLLING_NRFLAG The idle process is polling the TIF_NEED_RESCHED flag
TIF_MEMDIE The process is being destroyed to reclaim memory (see the section “The Out of Memory
Killer” in Chapter 17)
*/

ret_from_intr( );
ret_from_exception( );

#endif //end of __INTERRUPTS_EXCEPTIONS__H
